### ISSUE TITLE
AGCT.UnknownJavaErr5 dominates CPU time

### ISSUE THREAD

**Issue by crowlogic** [jvm-profiling-tools/honest-profiler#234]
![a](https://user-images.githubusercontent.com/23468326/34630783-265f1bc8-f233-11e7-81aa-c88e2e1350bd.png)

[sim.hpl.zip](https://github.com/jvm-profiling-tools/honest-profiler/files/1608079/sim.hpl.zip)

**Comment by nitsanw** [comment]
hi @crowlogic 
This is not a HP issue so much as an AsyncGetCallTrace issue.
Please see this page for details on how the samples are collected: https://github.com/jvm-profiling-tools/honest-profiler/wiki/How-are-samples-collected-by-honest-profiler
Typically UnknownJava errors are the result of a runtime generated stub (such as arraycopy, array fill, itable/vtable lookups, some string related methods etc) sample which the AsyncGetCallTrace cannot walk the stack out of (but knows it's Java because it's compiled code in the code cache).
If you were using JMC the profiler would simply ignore those samples. THAT IS THE WRONG THING TO DO.
You can try Async Profiler, which works around this issue to some extent, or use perf combined with perf-map-agent.
Thanks.

**Comment by crowlogic** [comment]
I see, thank you very much, that is good to know, I am indeed using System.arrayCopy quite a bit in that loop
